import { Outfit, Raleway } from "next/font/google";
import "./globals.css";
import RootLayoutWrapper from "@/layout-wrapper/root-layout-wrapper";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
  display: "swap",
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway",
});

export const metadata = {
  title: "School Education",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${outfit.variable} ${raleway.variable}`}>
      <body cz-shortcut-listen="true" className={`font-outfit antialiased w-full`}>
        <RootLayoutWrapper>
          <main>{children}</main>
        </RootLayoutWrapper>
      </body>
    </html>
  );
}
